=== hazardousholdings/unkj/installer/src/main/resources/app-config.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://unkj.hazardousholdings.com/configuration/app"
		   xmlns="http://unkj.hazardousholdings.com/configuration/app"
		   elementFormDefault="qualified">
	<xs:element name="application-config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="configuration" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="database">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="database">
											<xs:attribute name="key" type="xs:string" use="required" />
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="config">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="key" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="groups" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded" minOccurs="1">
							<xs:element name="group" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="database">
		<xs:all maxOccurs="1" minOccurs="1">
			<xs:element name="class-name" type="xs:string" maxOccurs="1" minOccurs="1" />
			<xs:element name="connection-string" type="xs:string" maxOccurs="1" minOccurs="1" />
			<xs:element name="username" type="xs:string" maxOccurs="1" minOccurs="1" />
			<xs:element name="password" type="xs:string" maxOccurs="1" minOccurs="1" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== hazardousholdings/unkj/installer/src/main/resources/app-config-example.xml
<?xml version="1.0" encoding="utf-8" ?>
<application-config xmlns="http://unkj.hazardousholdings.com/configuration/app"
			 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://unkj.hazardousholdings.com/configuration/app app-config.xsd">

	<configuration>
		<database key="ska">
			<class-name>org.postgresql.Driver</class-name>
			<connection-string>jdbc:postgresql://localhost:5432/unkj</connection-string>
			<username>ska</username>
			<password>ska</password>
		</database>
		<config key="log-level">WARNING</config>
	</configuration>

	<groups>
		<group>admins</group>
	</groups>

</application-config>
